using System.Linq;
using static ProceduralDungeon.Dice;
using static ProceduralDungeon.ItemsRepository;

namespace ProceduralDungeon
{
    public static class NpcsRepository
    {
        public static Npc[] All => new Npc[]
        {
            new Npc("Giant Rat",        001, challengeLevel: 1,       hp: 3,    category: CreatureCategory.Beast,
                inventory: Junk.RandomSample(D3.RollBaseZero()), gold: D8.RollBaseZero(),
                baseDescription: "It's frothing at the mouth and is missing patches of fur here and there."),
            new Npc("Cave Centipede",   002, challengeLevel: 3,       hp: 4,  ac: 10, dr: 1,    category: CreatureCategory.Beast,
                inventory: Junk.RandomSample(Coin.RollBaseZero()), gold: D12.RollBaseZero(),
                baseDescription: "Its body is covered in a protective layer of chitin and it has far too many legs."),
            new Npc("Crawling Hand",    012, challengeLevel: 1,       hp: 2,    category: CreatureCategory.Undead,
                inventory: Junk.RandomSample(Coin.RollBaseZero()), gold: D4.RollBaseZero(),
                damageDice: new Die[]{Coin},
                baseDescription: "This undead hand is animated by some foul magic."),
            new Npc("Zombie",           013, challengeLevel: 2,       hp: 5, dr: 1, category: CreatureCategory.Undead,
                inventory: Junk.RandomSample(D4.RollBaseZero()), gold: D10.RollBaseZero(),
                baseDescription: "Its eyes glow red and it emits a terrible stench of rotting flesh."),
            new Npc("Armored Zombie",   014, challengeLevel: 4,       hp: 5, ac: 10, dr: 1, category: CreatureCategory.Undead,
                inventory: Junk.RandomSample(D3.RollBaseZero()).Union(Armors.Where(a => a.Rarity == ItemRarity.Common).RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero()+3,
                baseDescription: "It still wears the decaying remnants of whatever armor it had on before death."),
            new Npc("Wight",            015, challengeLevel: 4,       hp: 4, dr: 1, category: CreatureCategory.Undead,
                attackRange: 3,
                inventory: Junk.RandomSample(D3.RollBaseZero()).Union(Uncommons.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero()+3,
                baseDescription: "Its body is more withered than a typical zombie, and it carries a staff through which it can cast spells."),
            new Npc("Animated Skeleton",016, challengeLevel: 4,       hp: 4, category: CreatureCategory.Undead,
                damageDice: new Die[]{D6},
                inventory: Junk.RandomSample(D3.RollBaseZero()).Union(Weapons.Where(a => a.Rarity == ItemRarity.Common).RandomSample(1)).ToList(), 
                gold: D10.RollBaseZero(),
                baseDescription: "Its eye sockets glow with a red light and its bones clatter with every movement. It still wields a crude weapon from its past life."),
            new Npc("Giant Viper",      003, challengeLevel: 4,       hp: 6,  ac: 9, category: CreatureCategory.Beast,
                damageDice: new Die[]{D8},
                inventory: Junk.RandomSample(D4.RollBaseZero()), gold: D12.RollBaseZero(),
                baseDescription: "Its enlarged fangs drip with venom and its body is corded with muscle."),
            new Npc("Cave Crocodile",   004, challengeLevel: 6,       hp: 10,  ac: 11, dr: 2,  category: CreatureCategory.Beast,
                damageDice: new Die[]{D6},
                inventory: Junk.RandomSample(D4.RollBaseZero()), gold: D20.RollBaseZero(),
                baseDescription: "Its toothy maw gapes open, waiting for any unwitting prey, and its body is covered in a thick reptilian hide."),
            new Npc("Hunter Spider",    005, challengeLevel: 5,       hp: 5,  ac: 9,    category: CreatureCategory.Beast,
                attackMod: 1,   damageDice: new Die[]{D8},
                inventory: Junk.RandomSample(D4.RollBaseZero()), gold: D12.RollBaseZero(),
                baseDescription: "It has long spindly legs and its body is covered in course hairs."),
            new Npc("Mummy",            016, challengeLevel: 5,       hp: 8, dr: 2, category: CreatureCategory.Undead,
                damageDice: new Die[]{D6}, damageMod: 2,
                inventory: Commons.RandomSample(D3.RollBaseZero()).Concat(Uncommons.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero() + D6.RollBaseZero() + 3,
                baseDescription: "The mummification process has preserved its musculature, making it stronger than a typical zombie."),
            new Npc("Ghoul",            017, challengeLevel: 6,       hp: 9, ac: 9, dr: 1, category: CreatureCategory.Undead,
                attackMod: 1, damageDice: new Die[]{D6}, damageMod: 1,
                inventory: Commons.RandomSample(D3.RollBaseZero()).Concat(Uncommons.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero() + D8.RollBaseZero() + 3,
                baseDescription: "More clever than most undead, ghouls hunt their prey with animal-like cunning."),
            new Npc("Banshee",          018, challengeLevel: 7,       hp: 8, ac: 10, category: CreatureCategory.Undead,
                attackMod: 1, damageDice: new Die[]{D4, D4},
                inventory: Commons.RandomSample(D3.RollBaseZero()).Concat(Uncommons.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero() + D10.RollBaseZero() + 3,
                baseDescription: "Appearing as the spectral figure of a gaunt elven woman, banshees have led many adventurers to their doom."),
            
            new Npc("Cave Bear",        006, challengeLevel: 8,     hp: 14,  ac: 10, dr: 3, searchRange: 6, category: CreatureCategory.Beast,
                damageDice: new Die[]{D6, D6},
                inventory: Commons.RandomSample(D4.RollBaseZero()).Concat(Uncommons.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D20.RollBaseZero(),
                baseDescription: "Its massive paws are the size of your head and its form is etched with scars from past battles."),
            new Npc("Rabid Wolf",       007, challengeLevel: 9,     hp: 9,   ac: 9, searchRange: 8, category: CreatureCategory.Beast,
                attackMod: 2, damageDice: new Die[]{D4, D4}, damageMod: 1,
                inventory: Commons.RandomSample(D3.RollBaseZero()), 
                gold: D12.RollBaseZero() + D6.RollBaseZero(),
                baseDescription: "It has bloodshot eyes and ragged fur. As it pants, yellowish-white foam drips from its mouth."),
            new Npc("Giant Poison Toad",008, challengeLevel: 9,     hp: 11,  ac: 10, dr: 1, category: CreatureCategory.Beast,
                attackRange: 2, attackMod: 3, damageDice: new Die[]{D4, D4},
                inventory: Commons.RandomSample(D3.RollBaseZero()).Concat(Uncommons.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D8.RollBaseZero() + D8.RollBaseZero(),
                baseDescription: "Its long tongue allows it to attack its enemies from range, and its bite could take off a man's head."),
            
            new Npc("Wraith",            019, challengeLevel: 9,       hp: 9, ac: 12, searchRange: 6, category: CreatureCategory.Undead,
                attackMod: 1, damageDice: new Die[]{D6, D6}, damageMod: 1,
                inventory: Uncommons.RandomSample(D3.RollBaseZero()).Concat(Rares.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero() + D12.RollBaseZero() + 3,
                baseDescription: "Its incorporial form resembles the ghostly shadow of a king, making it difficult to hit."),
            new Npc("Spitting Cobra",   009, challengeLevel: 12,       hp: 9,  ac: 10, 
                attackRange: 3, attackMod: 3, damageDice: new Die[]{D8, D8}, damageMod: 2,  category: CreatureCategory.Beast,
                inventory: Uncommons.RandomSample(D3.RollBaseZero()).Concat(Rares.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D8.RollBaseZero() + D8.RollBaseZero() + D8.RollBaseZero(),
                baseDescription: "Though small, its venomous spray is known to kill creatures ten times its size."),
            new Npc("Black Scorpion",   010, challengeLevel: 13,       hp: 10,  ac: 13, dr: 2,  category: CreatureCategory.Beast,
                attackMod: 2, damageDice: new Die[]{D12, D4, D4}, damageMod: 1,
                inventory: Uncommons.RandomSample(D3.RollBaseZero()).Concat(Rares.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D12.RollBaseZero() + D12.RollBaseZero(),
                baseDescription: "It possesses two massive claws and a deadly stinger at the end of its tail."),
            new Npc("Vampire",   021, challengeLevel: 11,       hp: 11,  ac: 10, dr: 2, searchRange: 6,
                attackMod: 2, damageDice: new Die[]{D4, D4, D4}, damageMod: 2,  category: CreatureCategory.Undead,
                inventory: Uncommons.RandomSample(D4.RollBaseZero()).Concat(Rares.RandomSample(D3.RollBaseZero())).ToList(), 
                gold: D8.RollBaseZero() + D8.RollBaseZero() + D8.RollBaseZero() + 4,
                baseDescription: "Known for their strength and endurance, vampires can persist after death as long as they feed on the blood of the living."),
            
            
            new Npc("Cave Mastodon",    011, challengeLevel: 15,   hp: 20,  ac: 13, dr: 4,  category: CreatureCategory.Beast,
                attackMod: 2, damageDice: new Die[]{D12, D12}, damageMod: 3,
                inventory: Uncommons.RandomSample(D4.RollBaseZero()).Concat(Rares.RandomSample(D3.RollBaseZero())).Concat(VeryRares.RandomSample(Coin.RollBaseZero())).ToList(), 
                gold: D20.RollBaseZero() + D20.RollBaseZero(),
                baseDescription: "It has two giant tusks and its hairy body is covered in a thick layer of protective fat."),
            new Npc("Lich",             020, challengeLevel: 13,       hp: 12,  ac: 11, dr: 2, searchRange: 8,
                attackRange: 4, attackMod: 4, damageDice: new Die[]{D8, D8}, damageMod: 3,  category: CreatureCategory.Undead,
                inventory: Rares.RandomSample(D3.RollBaseZero()).Concat(VeryRares.RandomSample(D3.RollBaseZero())).ToList(), 
                gold: D20.RollBaseZero() + D20.RollBaseZero() + 20,
                baseDescription: "Preserved by malign magic, this undead spellcaster wears regal robes and hovers slightly above the ground."),
        };
    }
}